### ISSUE TITLE
[suggest] For go mod package management

### ISSUE THREAD

**Issue by ywanbing** [gotuna/gotuna#1]
When I see that your web framework is based on 'github.com/gorilla' encapsulation, and when users use it, they call the 'github.com/gorilla' package to create 'Router', I think we can let "gotuna" call  "github.com/gorilla"," user call "gotuna" create of user need function or struct, and then manage the version of the package by the 'gotuna'; for the user,  only need to confirm the version of the package. 

My English is not good, this is through translation. 

---------中文----------
我看到你这个web框架都是基于 "github.com/gorilla"的封装，在用户使用时，还会调用"github.com/gorilla" 的包来创建"Router"，对此我认为可以让"gotuna" 来封装用户对  "github.com/gorilla" 调用，让用户调用 "gotuna"来满足需要的功能；
其中的至少有一个优点：
     由"gotuna" 统一管理"github.com/gorilla" 包的版本；对用户而言只需要确认"gotuna" 的版本。
     减少用户mod 依赖，减少用户管理负担。

**Comment by ywanbing** [comment]
截止现在，用时1个月，对于这个项目来说还处于新生状态，但是基础的功能都以可用，还是很了不起了。so 加油！

**Comment by alcalbg** [comment]
Hi,

Thanks for your feedback!

Yes, this is a good idea, I've added the constructor for the underlying router, can you check this on the 'development' branch? 

https://github.com/gotuna/gotuna/commit/97adcd91e164e9c9b1cd2b69f8cc5511960f107b

**Comment by ywanbing** [comment]
yes，I do！

**Comment by alcalbg** [comment]
fixed with #2
